### ISSUE TITLE
Support changes in multiple files

### ISSUE THREAD

**Issue by MichaelCurrin** [MichaelCurrin/auto-commit-msg#15]

**Comment by glassesUSA** [comment]
Just found this plugin and it looks amazing! Was wondering when the multiple files feature will be coming?

**Comment by MichaelCurrin** [comment]
Ah, thanks for the feedback.

I was taking a break from working on this as there wasn't interest, but with more stars and your comment I'm happy to get back to adding more features like this one (which will make my life easier). And I need a better install flow.

**Comment by MichaelCurrin** [comment]
On a first pass I'll do proposed Few Files functionality, as laid out in the Wiki.

https://github.com/MichaelCurrin/auto-commit-msg/wiki/Message-output-samples#few-files

Then later add the Many Files functionality which is next in the doc.

**Comment by MichaelCurrin** [comment]
I'd appreciate if you have any suggestions there on how you like those ideas or anything I thought of.

**Comment by MichaelCurrin** [comment]
I felt like hacking a few hours this evening, so made some good progress on this.

It is working for 2 to 4 files (named explicitly), with tests. I need to add the frontend integration still.

PR #29

**Comment by glassesUSA** [comment]
Looking great so far! Keeping posted :)

**Comment by MichaelCurrin** [comment]
Oh I had an idea I want to implement soon.

If the actions are mixed, I can't say `Create foo, bar, bazz` 

But I can easily do `Create foo, update bar and delete bazz`, where each path gets a verb.

**Comment by MichaelCurrin** [comment]
This was completed in #29 which is merged now!

Please try it out and let me know what you think.

Release [v0.18.](https://github.com/MichaelCurrin/auto-commit-msg/releases/tag/v0.18.0) with `.vsix` file.

See [Features](https://github.com/MichaelCurrin/auto-commit-msg/tree/v0.18.0#features) checklist for what is possible and what is on the roadmap.
