### ISSUE TITLE
Fix multi repo handling

### ISSUE THREAD

**Issue by MichaelCurrin** [MichaelCurrin/auto-commit-msg#19]
There is currently a _not implemented_ message setup to be raised on multiple repos in a workspace, but this did not actually trigger.

So either do that, or get the functionality to work in multiple repos (using the scope of the current scope files and message box (there are multiple).

**Comment by iSimar** [comment]
@MichaelCurrin Any updates on this? I would really like this feature.

**Comment by MichaelCurrin** [comment]
Thanks for the interest, I can add this to the next features to add.

**Comment by MichaelCurrin** [comment]
This is completed! https://github.com/MichaelCurrin/auto-commit-msg/releases/tag/v0.26.0
