### ISSUE TITLE
Filenames with spaces

### ISSUE THREAD

**Issue by dturaev** [MichaelCurrin/auto-commit-msg#70]
Thanks for this extension, I find it very useful. One problem is that I need to work with some files with spaces in their filenames (nothing I can do about it), and the extension splits the file name at the first blank space. Is there a way to let it handle filenames with any Unicode characters like spaces (and other characters, like Russian letters)?

**Comment by MichaelCurrin** [comment]
Hi thanks for your interest. 

I am aware of this as a bug but haven't bothered because it's a rare case for me.

Paths only need to be split by `/` so it should be easy for me to add support for spaces

**Comment by MichaelCurrin** [comment]
@dturaev how do you want to handle output? With quotes?

```
feat: create foo.txt
```
```
feat: create 'foo bar.txt'
```

**Comment by dturaev** [comment]
Great, thanks for the quick reply and for looking into this! I guess quotes are a good option in this case.

**Comment by MichaelCurrin** [comment]
I added quotes

**Comment by MichaelCurrin** [comment]
You're welcome to build the branch and try it out. Otherwise I can merge and release this myself soon anyway.

**Comment by MichaelCurrin** [comment]
```sh
git mv tslint.json 'ts lint.json'
```

Then generated msg:

![Screen Shot 2022-01-04 at 6 15 35 pm](https://user-images.githubusercontent.com/18750745/148089501-4f017cf7-3354-44c5-9f85-718a2aa5f205.png)

**Comment by MichaelCurrin** [comment]
Making a release with this now! :)

**Comment by dturaev** [comment]
Great, thanks a lot! This is really helpful.
