### ISSUE TITLE
Not generating message

### ISSUE THREAD

**Issue by glassesUSA** [MichaelCurrin/auto-commit-msg#77]
Since a recent update (I do not know when), I can no longer generate messages by clicking the button...

**Comment by MichaelCurrin** [comment]
Oh I'm sorry to hear that.

You probably auto updated to something a few weeks ago as v0.24.2 which was not significant and this installed version works fine for me today.

https://github.com/MichaelCurrin/auto-commit-msg/releases/tag/v0.24.2

Can you try remove and install again?

Or click the arrow next to Uninstall and "Install another version..." and pick another.

**Comment by glassesUSA** [comment]
Seems to be working fine now so idk what happened
