### ISSUE TITLE
Error on Windows - shell cannot spawn

### ISSUE THREAD

**Issue by RSNFreud** [MichaelCurrin/auto-commit-msg#93]
`A system error occurred (spawn C:\WINDOWS\system32\cmd.exe ENOENT)`

I get this error when trying to generate a message on windows

**Comment by RSNFreud** [comment]
What do you need a screenshot of? I press the commit button and the error shows

**Comment by RSNFreud** [comment]
workbench.desktop.main.js:sourcemap:774 Error: A system error occurred (spawn C:\WINDOWS\system32\cmd.exe ENOENT)
    at s.h (c:\Users\Freud\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:107798)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by martijn-megabite** [comment]
I'm getting the same message, since a couple of days, pressing the Auto Commit Message button triggers this error:
<img width="429" alt="2023-01-04 08_43_31" src="https://user-images.githubusercontent.com/47850778/210507083-199db060-55c7-4679-913f-94ed26738966.png">

`2023-01-04 08:44:53.331 [error] Error: spawn C:\Windows\system32\cmd.exe ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:283:19)
	at onErrorNT (node:internal/child_process:478:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21) commitMsg.autofill {"value":"MichaelCurrin.auto-commit-msg","c":"michaelcurrin.auto-commit-msg"}`

**Comment by MichaelCurrin** [comment]
Okay thanks for the info.

**Comment by elhakimyasya** [comment]
Yes, I also experienced this error

**Comment by TheWiresharkGuy** [comment]
Same ...

![image](https://user-images.githubusercontent.com/37513220/210768389-e0cf1525-0ed1-4170-998b-e03d13d1fba3.png)

**Comment by MichaelCurrin** [comment]
Okay thanks for the info. I was able to reproduce myself by running on Windows instead of WSL. I need to figure out how to get the debug mode to work so I can see more info logged

**Comment by MichaelCurrin** [comment]
Hmm I setup the extension in debug mode on Windows (the first time for me installing it on Windows). But I am not much closer to solving the issue.

---

The sandbox window does the error.

![image](https://user-images.githubusercontent.com/18750745/211518100-623107c5-1012-4728-bd38-d3501f06b89f.png)


The debug console doesn't show any errors. :/ 

![image](https://user-images.githubusercontent.com/18750745/211518030-dbb4a967-9bed-4b9f-ae51-64c2c3a4a361.png)

---


## More notes

Also there's no output from running this command regardless of staging or not (and it doesn't try find unstaged files).

```
git diff-index --name-status --find-renames --find-copies --no-color --cached HEAD
```

On multiple repo view, there's no error (but extension still doesn't work).

**Comment by CosmoFox** [comment]
@(but extension still doesn't work).@

**Comment by CosmoFox** [comment]
@(but extension still doesn't work).@
Same. Win11. No error. Not working.

**Comment by MichaelCurrin** [comment]
I figured out the cause. Using an invalid Linux-style current working directory causes the shell process to fail to spawn (for the Git command to run)

---

In getting the `rootUri` field, even on Windows it gets a Linux path. Which starts with `/` as absolute.

Printing `cwd`:

![image](https://user-images.githubusercontent.com/18750745/212172247-6cf4c1e2-a1dc-403a-bcf5-f6401e5546a5.png)


Like `/c:/Users/` is a bad path.

But `c:/Users/` (or `c:\Users\`) would be okay.

**Comment by MichaelCurrin** [comment]
Reported my problem in the vscode repo on this issue thread https://github.com/microsoft/vscode/issues/168758#issuecomment-1380969598

And I have hack in the meantime which works on a simple case - to replace the leading `/` for Windows-style paths that start as `/c:/`.

**Comment by MichaelCurrin** [comment]
I created PR #95 - any comments/reviews are welcome! 

I've done testing on my Windows machine and the fix worked.

I'll aim to release it in the next few days.

**Comment by MichaelCurrin** [comment]
Tested on Windows and released!

https://github.com/MichaelCurrin/auto-commit-msg/releases/tag/v0.26.1

**Comment by elhakimyasya** [comment]
Wow, thanks for fixing the issue @MichaelCurrin
